sudo: required
dist: trusty
language: rust
cache: cargo
os:
  - linux
  - osx
rust:
  - 1.13.0
  - stable
  - beta
  - nightly
matrix:
  allow_failure:
    - rust: nightly
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/install_openssl_deb.sh ; fi
script: scripts/run_tests.sh
after_success: scripts/run_kcov.sh
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=0fXi81cx3Khi8g0Q0mGqsABePoEdJfMcf
