sudo: required
dist: trusty
language: rust
rust: stable
cache: cargo

matrix:
  include:
    - os: osx
      rust: stable

    # min rust version
    - rust: 1.13.0
    - rust: beta
    - rust: nightly

  allow_failure:
    - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/install_openssl_deb.sh ; fi
script: scripts/run_tests.sh
after_success: scripts/run_kcov.sh
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=0fXi81cx3Khi8g0Q0mGqsABePoEdJfMcf
